#!/bin/bash

SCRIPTNAME=${0##*/}

function print_usage() {
    echo "$SCRIPTNAME <nginx version> [module_list]"
}

if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

## the script directory.
SCRIPT_DIR=$(dirname $0)

INSTALL_SCRIPT=$SCRIPT_DIR/nginx_module_install
[ -x $INSTALL_SCRIPT ] || exit 0

MODULE_LIST=${2-$SCRIPT_DIR/module_list.txt}

## Read the module list from a file.
while read m; do
    ## Skip all comment lines.
    skip=$(echo $m | awk '/^#.*$/ {print "skip"}')
    ## Process each listed module.
    test -z $skip && $INSTALL_SCRIPT $1 $m
done < $MODULE_LIST

