#!/bin/bash

### This script gets a given module for the nginx debian package build.

SCRIPTNAME=${0##*/}

## pkg-config.
PKGCONFIG=$(command -v pkg-config) || exit 0

## Usage.
function print_usage() {
    echo "$SCRIPTNAME <module directory> <install base directory>"
}

## Check the number of arguments.
if [ $# -ne 2 ]; then
    print_usage
    exit 1
fi

## Post processes a given module.
function post_process_module() {
    local temp_file=temp_conf.txt cflags ldflags

    case $1 in
        lua-nginx-module)
            rm -fr util
            cflags=$($PKGCONFIG --cflags luajit)
            ldflags=$($PKGCONFIG ----libs-only-l --libs luajitl)
            printf 'LUAJIT_INC="%s"\n' ${cflags#*I} >> $temp_file
            printf 'LUAJIT_LIB="%s"\n' $ldflags >> $temp_file
            cat $temp_file config > "0$temp_file"
            mv "0$temp_file" config
            [ -f $temp_file ] && rm $temp_file
            ;;
        nginx-sticky-module)
            rm -fr docs
            ;;
        ngx_devel_kit)
            rm -fr examples
            ;;
        nginx-upload-progress-module)
            rm -fr test
            ;;
    esac
} # post_process_module

## Source the variable definitions.
. $(dirname $0)/vars.sh

## Copying the module to the nginx build modules directory.
NGINX_MODULES_DIR=$2/debian/modules
[ -d $NGINX_MODULES_DIR ] || mkdir $NGINX_MODULES_DIR

CURR_DIR=$(pwd)

## The module directory.
MODULE_DIR=$NGINX_BASE_DIR/$1
[ -d $MODULE_DIR ] || exit 0

## Using git or svn to get the latest source.
cd $MODULE_DIR
GIT=$(command -v git) || exit 0
SVN=$(command -v svn) || exit 0

([ -d .git ] && $GIT pull) || ([ -d .svn ] && $SVN update)

## The destination directory.
DEST_DIR=$NGINX_MODULES_DIR/$1

## Create the module directory.
[ -d $DEST_DIR ] || mkdir $DEST_DIR

## Copying the files.
for i in $(ls); do
    cp -a $i $DEST_DIR
done

## Post process a module.
cd $DEST_DIR
post_process_module $1

## Return to the original directory.
cd $CURR_DIR

echo "Module installed in $DEST_DIR."
