#!/bin/bash

SCRIPTNAME=${0##*/}

function print_usage() {
    echo "$SCRIPTNAME -d [module install directory] [module_list]"
}

## Check the number of arguments.
if [ $# -gt 3 ]; then
    print_usage
    exit 1
fi

## Process command line arguments if given.
while getopts d: OPT; do
    case $OPT in
        d|+d)
            INSTALL_DIR="$OPTARG"
            ;;
        *)
            print_usage
            exit 2
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

## The script directory.
SCRIPT_DIR=$(dirname $0)

INSTALL_SCRIPT=$SCRIPT_DIR/nginx_module_install
[ -x $INSTALL_SCRIPT ] || exit 0

## Source the variable definitions.
. $(dirname $0)/vars.sh

NGINX_SOURCE_DIR=${INSTALL_DIR-$NGINX_BASE_DIR/nginx-debian-package}
[ -d $NGINX_SOURCE_DIR ] || exit 0

MODULE_LIST=${1-$SCRIPT_DIR/module_list.txt}

## Read the module list from a file.
while read m; do
    ## Skip all comment lines.
    skip=$(echo $m | awk '/^#.*$/ {print "skip"}')
    ## Process each listed module.
    test -z $skip && $INSTALL_SCRIPT $m $NGINX_SOURCE_DIR
done < $MODULE_LIST
