#!/bin/bash

### Install all auxiliary scripts for my Nginx package.

SCRIPTNAME=${0##*/}

function print_usage() {
    echo "$SCRIPTNAME [install directory] [nginx_ensite source directory]"
}

## Check the number of arguments.
if [ $# -gt 2 ]; then
    print_usage
    exit 1
fi

## The directories with the scripts.
NGINX_SCRIPTS_DIR=${2-$HOME/shell/nginx-ensite}

## Source the variable definitions.
. $(dirname $0)/vars.sh

## The nginx source dir. The argument $1 is the nginx version.
NGINX_SOURCE_DIR=${1-$NGINX_BASE_DIR/nginx-debian-package}
[ -d $NGINX_SOURCE_DIR ] || exit 0

## The destination directory.
DEST_DIR=$NGINX_SOURCE_DIR/debian
[ -d $DEST_DIR ] || exit 0

## Update the scripts.
cd $NGINX_SCRIPTS_DIR
GIT=$(command -v git) || exit 0
([ -d .git ] && $GIT pull)

## The files to copy.
SCRIPT_FILES=(
    man/nginx_dissite.8
    man/nginx_ensite.8
    man/nginx_ensite.8.ronn
    nginx_ensite
)

for f in ${SCRIPT_FILES[@]}; do
    cp $f $DEST_DIR
done

## The completion helper needs to be handled differently.
cp -a bash_completion.d $DEST_DIR
