#!/bin/bash

### Shell script that creates a tarball from a git repo of a bunch of
### configurations and extracts each of them in respective the debian
### package directory.

SCRIPTNAME=${0##*/}

function print_usage() {
    echo "$SCRIPTNAME [install directory] [configs source directory]"
}

## Check the number of arguments.
if [ $# -gt 2 ]; then
    print_usage
    exit 1
fi

## The configs to be packaged directory.
NGINX_CONFIGS_DIR=${2-$HOME/nginx-config/github}
[ -d $NGINX_CONFIGS_DIR ] || exit 0

## Source the variable definitions.
. $(dirname $0)/vars.sh

## The nginx source dir. The argument $1 is the nginx version.
NGINX_SOURCE_DIR=${1-$NGINX_BASE_DIR/nginx-debian-package}/debian/help/examples
[ -d $NGINX_SOURCE_DIR ] || exit 0

## CDing to the nginx configurations dir.
CURRENT_DIR=$(pwd)
cd $NGINX_CONFIGS_DIR

## Getting the tarballs and extracting it to the corresponding config
## dir of the debian package.
for d in $(ls -D); do
    cd $d
    ARCH_NAME=nginx_$d.tar.gz
    git archive HEAD | gzip > $ARCH_NAME
    OUTDIR=$NGINX_SOURCE_DIR/$d
    test -d $OUTDIR || mkdir -p $OUTDIR
    tar zxvf $ARCH_NAME -C $OUTDIR --exclude=.gitignore
    cd ..
done

## Going back to original dir.
cd $CURRENT_DIR
